# from django.urls import path
# from . import views

# urlpatterns = [
#     path('', views.add_recipe, name='recipe_add'),
# ]

# from django.urls import path
# from . import views

# urlpatterns = [
#     path("", views.recipe_list, name="recipe_list"),
#     path("create/", views.recipe_create, name="recipe_create"),
#     path("<int:pk>/update/", views.recipe_update, name="recipe_update"),
#     path("<int:pk>/delete/", views.recipe_delete, name="recipe_delete"),
#     path("recipe/<int:pk>/", views.recipe_detail, name="recipe_detail"),
# ]

# recipes/urls.py

from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

# This creates all the necessary API URLs for us (e.g., /api/recipes/, /api/recipes/1/)
router = DefaultRouter()
router.register(r'recipes', views.RecipeViewSet, basename='recipe-api')

urlpatterns = [
    # This now points to your new Class-Based View
    path('', views.RecipeListView.as_view(), name='recipe_list'),

    # The rest of your URLs for create, update, delete, and detail
    path('recipe/new/', views.recipe_create, name='recipe_create'),
    path('recipe/<int:pk>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/<int:pk>/edit/', views.recipe_update, name='recipe_update'),
    path('recipe/<int:pk>/delete/', views.recipe_delete, name='recipe_delete'),

    # This includes all the API URLs generated by the router
    path('api/', include(router.urls)),
]