# Generated by Django 5.2.5 on 2025-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password1', models.CharField(max_length=128, verbose_name='Password')),
                ('image', models.ImageField(blank=True, default='friends/default1.jpg', null=True, upload_to='friends/')),
            ],
        ),
    ]
