# Generated by Django 5.2.5 on 2025-09-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweetname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('festival', models.CharField(max_length=100)),
                ('servings', models.CharField(max_length=100)),
                ('preptime', models.IntegerField()),
                ('cooktime', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('mainingredients', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('cooking_method', models.CharField(max_length=100)),
                ('texture', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.friend')),
            ],
        ),
    ]
